# Generated by Django 5.2.17 on 2026-09-28 15:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def migrate_shipping_geography(apps, schema_editor):
    ShippingZone = apps.get_model("orders", "ShippingZone")
    Province = apps.get_model("orders", "Province")
    City = apps.get_model("orders", "City")
    Order = apps.get_model("orders", "Order")

    for zone in ShippingZone.objects.all():
        province, created = Province.objects.get_or_create(
            name=zone.province,
            defaults={
                "shipping_fee": zone.shipping_fee,
                "cod_fee": zone.cod_fee,
                "free_shipping_threshold": zone.free_shipping_threshold,
                "estimated_days": zone.estimated_days,
                "is_active": zone.is_active,
            },
        )
        if not created and zone.shipping_fee < province.shipping_fee:
            province.shipping_fee = zone.shipping_fee
            province.save(update_fields=["shipping_fee"])
        for city_name in zone.cities:
            City.objects.get_or_create(province=province, name=city_name)

    for order in Order.objects.select_related("shipping_zone"):
        zone = order.shipping_zone
        if not zone:
            continue
        province = Province.objects.filter(name=zone.province).first()
        city = City.objects.filter(province=province, name__iexact=order.city).first()
        order.delivery_province = province
        order.delivery_city = city
        order.save(update_fields=["delivery_province", "delivery_city"])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'cities',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('shipping_fee', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('cod_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estimated_days', models.CharField(default='2–5 business days', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.city'),
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='orders.province'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.province'),
        ),
        migrations.RunPython(migrate_shipping_geography, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='order',
            name='shipping_zone',
        ),
        migrations.DeleteModel(
            name='ShippingZone',
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('province', 'name'), name='unique_city_per_province'),
        ),
    ]
